version: '2'
services:
  lightnode:
    build: ./lightNode
    restart: on-failure
    entrypoint: /root/start.sh
    volumes:
      - ./files/rinkeby.json:/root/files/rinkeby.json:ro
      - ./files/keystore:/root/.ethereum/rinkeby/keystore:rw
      - ./files/rinkebychainlight:/root/.ethereum/rinkeby/geth/lightchaindata:rw
      - ./files/password:/root/files/password:ro
      # - /etc/localtime:/etc/localtime:ro
    command: '--datadir=~/.ethereum/rinkeby --networkid=4 --rpcapi "db,personal,eth,net,web3" --rpccorsdomain="*" --rpc --rpcaddr="0.0.0.0" --syncmode=light --bootnodes="enode://a24ac7c5484ef4ed0c5eb2d36620ba4e4aa13b8c84684e1b4aab0cebea2ae45cb4d375b77eab56516d34bfbd3c1a833fc51296ff084b770b94fb9028c4d25ccf@52.169.42.101:30303?discport=30304"'
    ports:
      - "8545:8545"

  fullnode:
    build: ./lightNode
    restart: on-failure
    entrypoint: /root/start.sh
    volumes:
      - ./files/rinkeby.json:/root/files/rinkeby.json:ro
      - ./files/rinkebychain:/root/.ethereum/rinkeby/geth/chaindata:rw
      - ./files/keystore:/root/.ethereum/rinkeby/keystore:rw
      - ./files/password:/root/files/password:ro
      # - /etc/localtime:/etc/localtime:ro
    command: '--datadir=~/.ethereum/rinkeby --networkid=4 --cache=512 --rpcapi "db,personal,eth,net,web3" --rpccorsdomain="*" --rpc --rpcaddr="0.0.0.0" --bootnodes="enode://a24ac7c5484ef4ed0c5eb2d36620ba4e4aa13b8c84684e1b4aab0cebea2ae45cb4d375b77eab56516d34bfbd3c1a833fc51296ff084b770b94fb9028c4d25ccf@52.169.42.101:30303?discport=30303"'
    ports:
      - "10545:8545"
